-- Composer v0.12: sources on Worth watching, and a Worth a shrug that
-- doesn't write the same sentence five times.
--
-- Two reader-visible complaints, one prompt change each, plus one
-- structural fix because the second complaint was not really a prompt
-- problem.
--
-- 1. Worth watching had no citations. Every other body section links
--    out; this one asserted something about a live thread and asked the
--    reader to take it on trust. The input has always carried
--    source_url + additional_source_urls — the prompt just said not to
--    use them, on the theory that a ~15–25-word ceiling had no room. It
--    does: the ceiling is about prose, and a citation cluster isn't
--    prose. Capped at two domains so the line still scans.
--
-- 2. Worth a shrug read as a template with the nouns swapped:
--
--      "X asked whether Y — a question that will feel urgent until Z."
--      "A told reporters B — which is the kind of personal update that
--       generates a news cycle and then dissolves."
--      "C hired a detective — the sort of story that writes its own
--       punchline and then runs out of road."
--
--    Subject, verb, em-dash, relative clause predicting the item's own
--    decay, five times. Two of the prompt's five target moves are the
--    only ones that apply to anything at all, so the model reached for
--    those two every week. v0.12 makes the moves a no-repeat rota,
--    bans the "which is the kind of thing that…" / "forgotten by
--    {weekday}" frames by name, requires length variation (at least one
--    item under 15 words), and adds a move that has no punchline at all.
--    Also bans shrug lines that comment on the brief's own structure
--    ("this also appears in the conversation section above").
--
--    But the labels were identical too — five "48-hour controversy"
--    tags — and no amount of prompt could fix that, because it was a
--    selection artifact. Shrug candidates were ranked by source_count,
--    and controversy_flash is *by definition* the marker of a story the
--    wires piled onto, so the ranking was very nearly a
--    controversy_flash sort. in_circle_hype (a niche launch two trade
--    outlets covered) could never win that race. compose-shrug.ts now
--    spends the five slots round-robin across the qualifying factors,
--    ranking by source_count within each, and hands the composer a
--    pre-chosen `label` per row instead of a menu — same reason the
--    composer doesn't choose its own section (CLAUDE.md §Invariants #2).
--
-- Bumping the version string invalidates composer cache-on-hash lookups,
-- forcing fresh output against the corrected prompt.

UPDATE config
SET value = '"composer-v0.12"'::jsonb, updated_at = now()
WHERE key = 'composer.prompt_version';
